fix?
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.mms/com.android.mms.ui.SingleRecipientConversationActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class <unknown>
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2730)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2791)
 at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:163)
 at android.app.ActivityThread.main(ActivityThread.java:6343)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
 at android.view.LayoutInflater.createView(LayoutInflater.java:652)
 at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:742)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:810)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
 at com.android.mms.ui.ConversationBase.initResourceRefs(Unknown Source)
 at com.android.mms.ui.SingleRecipientConversationActivity.initResourceRefs(Unknown Source)
 at com.android.mms.ui.MessageEditableActivityBase.onCreate(Unknown Source)
 at com.android.mms.ui.ConversationBase.onCreate(Unknown Source)
 at com.android.mms.ui.SingleRecipientConversationActivity.onCreate(Unknown Source)
 at android.app.Activity.performCreate(Activity.java:6858)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2683)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2791)
 at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:163)
 at android.app.ActivityThread.main(ActivityThread.java:6343)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: java.lang.IndexOutOfBoundsException: setSpan (39 ... 84) ends beyond length 59
 at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:427)
 at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:154)
 at android.text.SpannableString.setSpan(SpannableString.java:46)
 at android.content.res.StringBlock.applyStyles(StringBlock.java:187)
 at android.content.res.StringBlock.get(StringBlock.java:134)
 at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:310)
 at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1219)
 at android.content.res.TypedArray.getText(TypedArray.java:167)
 at android.content.res.MiuiTypedArray.getText(MiuiTypedArray.java:23)
 at android.widget.TextView.<init>(TextView.java:1006)
 at android.widget.TextView.<init>(TextView.java:704)
 at android.widget.Tex